# Generated by Django 5.2.4 on 2025-10-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draz', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='peice',
            new_name='price',
        ),
    ]
