# Generated by Django 5.2.4 on 2025-10-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draz', '0003_rename_peice_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
